### ISSUE TITLE
"Reported from in-game: ore not getting added to whitelist" - submitted via. helper utility

### ISSUE THREAD

**Issue by hamstar0** [NanobotZ/tml_VeinMiner_mod#11]
| Mods:  | - | - |
| :--- | :--- | :--- |
| `Antisocial 1.0` | `Boss Checklist 0.2.1` | `Elements Awoken Music 0.1.1.3` |
| `Elements Awoken 1.3.7.6` | `Mod Helpers 4.4.0` | `Even More Modifiers 0.1.2.3` |
| `Luiafk 1.0.0.130` | `Magic Storage 0.4.3.3` | `MaxStackPlus 21.0` |
| `More Chest Loot 0.6` | `Recipe Browser 0.7.2` | `Reforge Armor 1.0` |
| `Shadows of Abaddon (SacredTools) 1.1.0.1` | `Spirit Mod 1.3.4.1` | `Thorium Mod 1.6.0.2` |
| `Universe Of Swords Mod 2.8` | `VeinMiner 1.3.0.5` | `WeaponOut 1.6.3` |
| `Wildlife Mod 0.12.0` | `Wing Slot 1.6.2` | - |
 
| Name | Male | Has Demon Heart | Difficulty mode | Life | Mana | Defense |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| mr boots | True | False | 0 | 159 of 159 (140) | 80 of 80 | 34 |
 
**Player mr boots's (0) equipment:**
 
| Head | Body | Legs | Accessory 1 | Accessory 2 | Accessory 3 | Accessory 4 | Accessory 5 | Vanity 1 | Vanity 2 | Vanity 3 | Vanity 4 | Vanity 5 | Vanity 6 | Vanity 7 | Vanity 8 |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| Armored Living Wood Mask | Jagged Living Wood Chestguard | Armored Living Wood Boots | Brisk Round Shield | Meat Shield | Gold Aegis | Armored Shackle | Menacing Shoe Spikes | Intrepid Crier's Cap | Menacing Crier's Sash | Brisk Crier's Leggings | Magnifying Glass | Quick Aglet | Spiked Opal Ring | Menacing Zephyr | Rusty Buckler |
 
Is day: True, Time of day/night: 52469, Elapsed half days: 34
 
World name: brains? nah, world size: Large
 
World progress: none
 
Items on ground: 58, Npcs active: 7
 
Player count: 1 (single-player)
 
Autopause: False
 
Autosave: True
 
Lighting mode: 0
 
Lighting threads: 0
 
Frame skip mode: 2
 
Is screen maximized: False
 
Screen resolution: 1366 768
 
Quality style: 0
 
Background on: True
 
Child safety: False
 
Game zoom: 1
 
UI zoom: 1
 
 
 
Recent error logs:
```
Mod Helpers updated to 4.4.0
```
 
Damascus ore from Universe of swords mod isnt getting added to white list

**Comment by NanobotZ** [comment]
Just checked - it works.
When trying to add something to the white list please notice if you have smart cursor enabled, if it's enabled it's not adding a tile your mouse cursor is over - it's adding the tile your smart cursor is highlighting.
I also added that ore to the online ore list - should be "veinmine'able" now without adding it to the list manually, just restart your game or reload the mods.
