### ISSUE TITLE
"Reported from in-game: Whitelist in Multiplayer" - submitted via. helper utility

### ISSUE THREAD

**Issue by hamstar0** [NanobotZ/tml_VeinMiner_mod#12]
| Mods:  | - | - |
| :--- | :--- | :--- |
| `AlchemistNPC 8.4` | `Auto Trash 0.4` | `Boss Highlights 1.0.0` |
| `Boss Checklist 0.2.1` | `Prefixes For Enemies 2.0.0` | `Fargo's Mutant Mod 1.3` |
| `Yet Another Boss Health Bar 1.3.2` | `Mod Helpers 4.4.0` | `imkSushi's Mod 4.3.1` |
| `Luiafk 1.0.0.130` | `Magic Storage 0.4.3.3` | `MaxStackPlus 21.0` |
| `No More Tombs 1.0.1` | `OmniSwing 2.1` | `Recipe Browser 0.7.2` |
| `Thorium Mod 1.6.0.4` | `VeinMiner 1.3.0.5` | `WeaponOut 1.6.3` |
| `Which Mod Is This From? (WMITF) 2.6` | - | - |
 
| Name | Male | Has Demon Heart | Difficulty mode | Life | Mana | Defense |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| Gungnir | True | False | 0 | 100 of 100 | 20 of 20 | 1 || Russian Kamakazi | True | False | 0 | 100 of 100 | 20 of 20 | 1 |
 
**Player Gungnir's (0) equipment:**
 
| Accessory 1 | Accessory 2 | Vanity 1 | Vanity 2 | Vanity 3 |
| :--- | :--- | :--- | :--- | :--- |
| Family Heirloom | Guide to Plant Fiber Cordage | Wood Helmet | Wood Breastplate | Wood Greaves |
 
**Player Russian Kamakazi's (1) equipment:**
 
| Accessory 1 |
| :--- |
| Family Heirloom |
 
Is day: True, Time of day/night: 15351, Elapsed half days: 10
 
World name: Poopland, world size: Medium
 
World progress: none
 
Items on ground: 248, Npcs active: 18
 
Player count: 2 (multiplayer)
 
Autopause: False
 
Autosave: True
 
Lighting mode: 0
 
Lighting threads: 0
 
Frame skip mode: 2
 
Is screen maximized: True
 
Screen resolution: 1536 800
 
Quality style: 0
 
Background on: True
 
Child safety: False
 
Game zoom: 1
 
UI zoom: 1
 
 
 
Recent error logs:
```
Mod Helpers updated to 4.4.0
1:001:00000 - 000007.43   HamstarHelpers.PlayerLogic.OnCurrentClientEnterWorld - No (old) UID for Russian Kamakazi (1) to send to server
```
 
Multiplayer whitelisting dosent work

**Comment by NanobotZ** [comment]
Modify the `"ModifyingWhitelistOnMultiplayer": false` in the config (located in `Documents\My Games\Terraria\ModLoader\Mod Configs\VeinMiner.json`) from `false` to `true`
