### ISSUE TITLE
"Reported from in-game: doesnt work" - submitted via. helper utility

### ISSUE THREAD

**Issue by hamstar0** [NanobotZ/tml_VeinMiner_mod#13]
| Mods:  | - | - |
| :--- | :--- | :--- |
| `AFK's PETS and more 9.9.7.8` | `AlchemistNPC 8.4` | `Antisocial 1.1` |
| `Auto Trash 0.4` | `Boss Checklist 0.2.1` | `Calamity Mod (No Calamity Music) 1.4.2.4` |
| `Consolaria\. Console exclusives and more\. 1.0.6` | `Do it with a copper shortsword\! 0.1.0.1` | `Health and Mana From Bosses 1.1.2.1` |
| `Extensible Inventory 1.4.1` | `Fargo's Mutant Mod 1.3` | `Faster Weapons 1.0` |
| `Faster Tools 1.0.1` | `Yet Another Boss Health Bar 1.3.2` | `Gambler NPC 0.1` |
| `Mod Helpers 4.4.0` | `ItemMagnetPlus 0.1.10` | `JoJoStands 1.43.9` |
| `Even More Modifiers 0.1.2.3` | `Loot Bags 1.0.1` | `Luiafk 1.0.0.130` |
| `Magic Storage 0.4.3.3` | `Megium\: Gods and More 0.1.3` | `MoreAccesories+ 2.3` |
| `More Chest Loot 0.6` | `OmniSwing 2.1` | `\[c/39C117\:PickCrafter Mod (A lot of Pickaxes)\] 0.2.7` |
| `Plentiful Ores 1.3` | `Recipe Browser 0.7.2` | `Reduced Grinding 4.66` |
| `Shadows of Abaddon (SacredTools) 1.1.0.3` | `Sell Slot 0.1.0.2` | `Shitty Destruction 0.1.2.0` |
| `Shop Expander 1.1.2` | `Start with base 0.2.2.2` | `SuperQuickRespawn 1.0.1` |
| `The Luggage 0.1.3` | `Ultranium Mod 0.5.4.6` | `VeinMiner 1.3.0.5` |
| `WeaponOut 1.6.4` | `Wing Slot 1.6.2` | `Which Mod Is This From? (WMITF) 2.6` |
| `WorldGen Previewer 0.3` | `Item Stats+ 1.3.2` | - |
 
| Name | Male | Has Demon Heart | Difficulty mode | Life | Mana | Defense |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| aaaaa | True | True | 0 | 1076 of 1076 (500) | 301 of 301 (200) | 101 |
 
**Player aaaaa's (0) equipment:**
 
| Head | Body | Legs | Accessory 1 | Accessory 2 | Accessory 3 | Accessory 4 | Accessory 5 | Accessory 6 | Vanity 1 | Vanity 2 | Vanity 3 | Vanity 4 | Vanity 5 | Vanity 6 | Vanity 7 | Vanity 8 | Vanity 9 |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| Beetle Helmet | Beetle Shell | Beetle Leggings | Menacing Astral Bulwark | Shark Tooth Necklace | Blood Pact | Statis' Ninja Belt | Quick Celestial Shell | Jagged Fire Gauntlet | Horned God Mask | Horned God Robe | Horned God Boots | Quick Asgard's Valor | Angel Treads | Rash Aquatic Emblem | Intrepid Bloody Worm Scarf | Void of Extinction | Cryo Stone |
 
Is day: True, Time of day/night: 757, Elapsed half days: 76
 
World name: aaaaa, world size: Medium
 
World progress: Eye of Cthulhu killed, King Slime killed, Queen Bee killed, Brain of Cthulhu killed, Skeletron killed, Wall of Flesh killed, Destroyer killed, Twins killed, Skeletron Prime killed, Plantera killed, Golem killed, Duke Fishron killed, Ancient Cultist killed
 
Items on ground: 2, Npcs active: 41
 
Player count: 1 (multiplayer)
 
Autopause: False
 
Autosave: True
 
Lighting mode: 0
 
Lighting threads: 0
 
Frame skip mode: 2
 
Is screen maximized: False
 
Screen resolution: 1360 768
 
Quality style: 0
 
Background on: True
 
Child safety: False
 
Game zoom: 1
 
UI zoom: 1
 
 
 
Recent error logs:
```
No error logs available.
```
 
doesnt say it is on and doesnt turn on

**Comment by NanobotZ** [comment]
Make sure mod is enabled, also make sure the key is bound.
