### ISSUE TITLE
"Reported from in-game: Thorium Mod ; Onyx" - submitted via. helper utility

### ISSUE THREAD

**Issue by hamstar0** [NanobotZ/tml_VeinMiner_mod#14]
| Mods:  | - | - |
| :--- | :--- | :--- |
| `Base Mod 1.0.8.8` | `Boss Checklist 0.2.1` | `Boss Cursor 1.2.1` |
| `Cheat Sheet 0.5.0.2` | `Extensible Inventory 1.4.1.3` | `Fargo's Mutant Mod 1.3.6.2` |
| `Mod Helpers 4.4.0.2` | `HERO's Mod 0.2.5` | `imkSushi's Mod 4.3.1` |
| `Even More Modifiers 0.1.2.3` | `No More Tombs 1.0.1` | `Recipe Browser 0.7.3` |
| `Shorter Respawn Time 0.2.5` | `Thorium Mod 1.6.0.4` | `VeinMiner 1.3.0.5` |
| `WeaponOut 1.6.4` | `Wing Slot 1.6.2` | - |
 
| Name | Male | Has Demon Heart | Difficulty mode | Life | Mana | Defense |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| A2 | True | False | 0 | 132 of 132 (120) | 20 of 20 | 14 |
 
**Player A2's (0) equipment:**
 
| Head | Body | Legs | Accessory 1 | Accessory 2 | Accessory 3 | Accessory 4 | Accessory 5 | Vanity 1 |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| Silver Helmet | Silver Chainmail | Silver Greaves | Radar | Rash Climbing Claws | Violent Iron Shield | Band of Regeneration | Hermes Boots | Family Heirloom |
 
Is day: False, Time of day/night: 20153, Elapsed half days: 3
 
World name: A2, world size: Large
 
World progress: none
 
Items on ground: 61, Npcs active: 9
 
Player count: 1 (single-player)
 
Autopause: False
 
Autosave: True
 
Lighting mode: 0
 
Lighting threads: 0
 
Frame skip mode: 1
 
Is screen maximized: False
 
Screen resolution: 1366 768
 
Quality style: 3
 
Background on: False
 
Child safety: False
 
Game zoom: 1
 
UI zoom: 1
 
 
 
Recent error logs:
```
No error logs available.
```
 
It doesent work with VM

**Comment by NanobotZ** [comment]
Not enough information.
