### ISSUE TITLE
"Reported from in-game: whitelist not working" - submitted via. helper utility

### ISSUE THREAD

**Issue by hamstar0** [NanobotZ/tml_VeinMiner_mod#15]
| Mods:  | - | - |
| :--- | :--- | :--- |
| `AlchemistNPC 8.5` | `Auto Trash 0.4` | `Boss Checklist 0.2.1` |
| `Consolaria\. Console exclusives and more 1.1.2` | `Extensible Inventory 1.4.1.3` | `Fargo's Mutant Mod 1.3.6.2` |
| `Fargo's Soul Mod 0.7.3.1` | `Yet Another Boss Health Bar 1.3.2` | `Mod Helpers 4.4.0.5` |
| `Happiiny's Miscellaneous Recipes 1.1` | `imkSushi's Mod 4.3.1` | `JoostMod 0.7.2.12` |
| `Magic Storage 0.4.3.3` | `Pumpking's Mod 1.1.4.1` | `Quality of Life\: Recipes 1.5.0` |
| `Recipe Browser 0.7.3` | `Reduced Grinding 4.68` | `Spirit Mod 1.3.4.1` |
| `SuperQuickRespawn 1.0.1` | `More Spell Books 0.4.0` | `Thorium Mod 1.6.0.4` |
| `VeinMiner 1.3.0.5` | `Wing Slot 1.6.2` | `Which Mod Is This From? (WMITF) 2.6` |
 
| Name | Male | Has Demon Heart | Difficulty mode | Life | Mana | Defense |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| Multella | True | False | 0 | 100 of 100 | 20 of 20 | 1 || Amagay\! | False | False | 0 | 100 of 100 | 20 of 20 | 7 |
 
**Player Multella's (0) equipment:**
 
| Accessory 1 | Vanity 1 | Vanity 2 | Vanity 3 |
| :--- | :--- | :--- | :--- |
| Family Heirloom | Parka Hood | Parka Coat | Parka Pants |
 
**Player Amagay\!'s (1) equipment:**
 
| Head | Body | Legs | Accessory 1 | Accessory 2 | Accessory 3 | Vanity 1 | Vanity 2 | Vanity 3 |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| Leather Hood | Leather Plate | Leather Boots | Gnunderson's Shackle | Family Heirloom | Menacing Climbing Claws | Graydee's Mask | Wolf Shirt | Wolf Pants |
 
Is day: True, Time of day/night: 23596, Elapsed half days: 4
 
World name: Multopia, world size: Medium
 
World progress: none
 
Items on ground: 16, Npcs active: 14
 
Player count: 2 (multiplayer)
 
Autopause: False
 
Autosave: True
 
Lighting mode: 0
 
Lighting threads: 0
 
Frame skip mode: 2
 
Is screen maximized: False
 
Screen resolution: 1366 768
 
Quality style: 0
 
Background on: True
 
Child safety: False
 
Game zoom: 1
 
UI zoom: 1
 
 
 
Recent error logs:
```
1:000:00000 - 000094.86   HamstarHelpers.PlayerDataProtocol.ReceiveOnClient - Inactive player indexed as 1
```
 
the buttonfor enabling the selected block to be whitelisted does not work

**Comment by NanobotZ** [comment]
Modify the `"ModifyingWhitelistOnMultiplayer": false` in the config (located in `Documents\My Games\Terraria\ModLoader\Mod Configs\VeinMiner.json`) from `false` to `true`
