### ISSUE TITLE
"Reported from in-game: It Doesn't work" - submitted via. helper utility

### ISSUE THREAD

**Issue by hamstar0** [NanobotZ/tml_VeinMiner_mod#16]
| Mods:  | - | - |
| :--- | :--- | :--- |
| `Auto Trash 0.4` | `Cheat Sheet 0.5.0.2` | `Health and Mana From Bosses 1.1.2.1` |
| `Various Weathers 1.0.0.6` | `Fargo's Mutant Mod 1.3.6.2` | `Yet Another Boss Health Bar 1.3.2` |
| `Mod Helpers 4.4.0.5` | `Loot Bags 1.0.1` | `More Chest Loot 0.6` |
| `Plentiful Ores 1.3` | `Reduced Grinding 4.68` | `Simple Auto Chests 1.1.1` |
| `Thorium Mod 1.6.0.4` | `VeinMiner 1.3.0.5` | - |
 
| Name | Male | Has Demon Heart | Difficulty mode | Life | Mana | Defense |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| Mod tester | True | False | 0 | 100 of 100 | 20 of 20 | 3 |
 
**Player Mod tester's (0) equipment:**
 
| Accessory 1 | Accessory 2 | Accessory 3 |
| :--- | :--- | :--- |
| Aglet | Garras para Escalada (Protetor) | Algema (Rápido) |
 
Is day: False, Time of day/night: 26321, Elapsed half days: 1
 
World name: mundo, world size: Small
 
World progress: none
 
Items on ground: 35, Npcs active: 36
 
Player count: 1 (single-player)
 
Autopause: False
 
Autosave: True
 
Lighting mode: 0
 
Lighting threads: 0
 
Frame skip mode: 2
 
Is screen maximized: True
 
Screen resolution: 1024 704
 
Quality style: 0
 
Background on: True
 
Child safety: False
 
Game zoom: 1
 
UI zoom: 1
 
 
 
Recent error logs:
```
[c/4bd5ff:Vitality Mod]: HeadlessZombie. You have set ModNPC.banner or ModNPC.bannerItem, but not the other. Make sure you set both, check your spelling, and that the item exists if you are using mod.ItemType(). Report this to the [c/4bd5ff:Vitality Mod] developers.
[c/4bd5ff:Vitality Mod]: RustSkeleton. You have set ModNPC.banner or ModNPC.bannerItem, but not the other. Make sure you set both, check your spelling, and that the item exists if you are using mod.ItemType(). Report this to the [c/4bd5ff:Vitality Mod] developers.
Failed to read Loot Bag config file! Recreating config...
0:000:00000 - 000027.87   !HamstarHelpers.PlayerLogic.OnSingleEnterWorld - No (old) UID for Mod tester (0)
Mod configs reloaded for FKBossHealthBar, HamstarHelpers, LootBags, VeinMiner
```
 
simply doesn't work

**Comment by NanobotZ** [comment]
Not enough information, most possibly the Veinmine key not bound to anything.
