### ISSUE TITLE
"Reported from in-game: no whitelist" - submitted via. helper utility

### ISSUE THREAD

**Issue by hamstar0** [NanobotZ/tml_VeinMiner_mod#17]
| Mods:  | - | - |
| :--- | :--- | :--- |
| `Yet Another Boss Health Bar 1.3.2` | `Mod Helpers 4.4.0.5` | `Loot Bags 1.0.1` |
| `Max Stack Plus Extra 1.0.2` | `More Chest Loot 0.6` | `No More Tombs 1.0.1` |
| `Rewards 2.1.1.1` | `Shorter Respawn Time 0.2.5` | `Thorium Mod 1.6.0.4` |
| `VeinMiner 1.3.0.5` | `Where's My Items 0.5.1` | `Wildlife Mod 0.12.0` |
 
| Name | Male | Has Demon Heart | Difficulty mode | Life | Mana | Defense |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| god | True | False | 0 | 18 of 100 | 20 of 20 | 0 || Dash | False | False | 0 | 104 of 180 | 20 of 20 | 1 || IDK | True | False | 0 | 100 of 100 | 20 of 20 | 2 |
 
**Player god's (0) equipment:**
 
| Accessory 1 |
| :--- |
| Hermes Boots |
 
**Player Dash's (1) equipment:**
 
| Accessory 1 | Accessory 2 | Accessory 3 | Accessory 4 | Accessory 5 | Vanity 1 | Vanity 2 |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| Family Heirloom | Precise Aglet | Guide to Plant Fiber Cordage | Angry Radar | Hermes Boots | Rain Hat | Rain Coat |
 
**Player IDK's (2) equipment:**
 
| Head | Body | Vanity 1 |
| :--- | :--- | :--- |
| Wood Helmet | Wood Breastplate | Umbrella Hat |
 
Is day: False, Time of day/night: 6444, Elapsed half days: 5
 
World name: modded survival, world size: Medium
 
World progress: none
 
Items on ground: 176, Npcs active: 14
 
Player count: 3 (multiplayer)
 
Autopause: False
 
Autosave: True
 
Lighting mode: 0
 
Lighting threads: 7
 
Frame skip mode: 1
 
Is screen maximized: False
 
Screen resolution: 1476 830
 
Quality style: 1
 
Background on: True
 
Child safety: False
 
Game zoom: 1
 
UI zoom: 1.300752
 
 
 
Recent error logs:
```
1:001:00000 - 000355.50   Rewards.RewardsWorld.Initialize
1:001:00001 - 000358.03   !Rewards.RewardsPlayer.OnConnectCurrentClient - Player Dash (1) not active
1:001:00002 - 002455.57   HamstarHelpers.PlayerDataProtocol.ReceiveOnClient - Inactive player indexed as 0
1:001:00003 - 002568.88   HamstarHelpers.PlayerDataProtocol.ReceiveOnClient - Inactive player indexed as 2
1:001:00004 - 002600.96   Rewards.KillData.ResetAll - PP reset (for Dash)
1:001:00005 - 002600.97   Rewards.KillData.ResetAll - PP reset (for Dash)
1:001:00006 - 003227.80   HamstarHelpers.PlayerDataProtocol.ReceiveOnClient - Inactive player indexed as 0
```
 
wont allow adding stone to whitelist

**Comment by NanobotZ** [comment]
https://github.com/NanobotZ/tml_VeinMiner_mod/issues/15#issuecomment-508525017
