### ISSUE TITLE
"Reported from in-game: VeinMiner 1.3.0.5 " - submitted via. helper utility

### ISSUE THREAD

**Issue by hamstar0** [NanobotZ/tml_VeinMiner_mod#18]
| Mods:  | - | - |
| :--- | :--- | :--- |
| `Auto Trash 0.4` | `Banner Bonanza 1.1` | `Boss Checklist 0.2.1` |
| `Extensible Inventory 1.4.1.3` | `Mod Helpers 4.4.0.5` | `Helpful Hotkeys 1.5.6` |
| `imkSushi's Mod 4.3.1` | `Item Checklist 0.5.2` | `Magic Storage 0.4.3.3` |
| `Max Stack Plus Extra 1.0.2` | `Recipe Browser 0.7.3.1` | `Reduced Grinding 4.68` |
| `Start with base 0.2.2.2` | `Thorium Mod 1.6.0.4` | `VeinMiner 1.3.0.5` |
| `Where's My Items 0.5.1` | - | - |
 
| Name | Male | Has Demon Heart | Difficulty mode | Life | Mana | Defense |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| OJ07 | True | False | 0 | 400 of 400 | 200 of 200 | 23 || Avanju | True | False | 0 | 400 of 400 | 180 of 180 | 23 |
 
**Player OJ07's (0) equipment:**
 
| Head | Body | Legs | Accessory 1 | Accessory 2 | Accessory 3 | Accessory 4 | Accessory 5 | Vanity 1 | Vanity 2 | Vanity 3 | Vanity 4 | Vanity 5 | Vanity 6 |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| Flight Hat | Flight Mail | Flight Boots | Spiked Shield of Cthulhu | Armored Band of Regeneration | Menacing Cloud in a Balloon | Armored Frostspark Boots | Angry Shark Tooth Necklace | Pharaoh's Mask | Pharaoh's Robe | Obsidian Horseshoe | Quick Guide to Expert Throwing | Menacing Sea Breeze Pendant | Guide to Plant Fiber Cordage |
 
**Player Avanju's (2) equipment:**
 
| Head | Body | Legs | Accessory 1 | Accessory 2 | Accessory 3 | Accessory 4 | Accessory 5 | Vanity 1 | Vanity 2 |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| Tide Hunter's Cap | Tide Hunter Chestpiece | Tide Hunter Leggings | Hasty Shark Tooth Necklace | Armored Shield of Cthulhu | Violent Ring of Unity | Rash Frostspark Boots | Warding Band of Regeneration | Warding Tungsten Bulwark | Jagged Lava Waders |
 
Is day: False, Time of day/night: 3332, Elapsed half days: 31
 
World name: STARDWE VALLEY, world size: Large
 
World progress: Eye of Cthulhu killed, King Slime killed, Brain of Cthulhu killed
 
Items on ground: 26, Npcs active: 35
 
Player count: 2 (multiplayer)
 
Autopause: False
 
Autosave: True
 
Lighting mode: 0
 
Lighting threads: 0
 
Frame skip mode: 2
 
Is screen maximized: True
 
Screen resolution: 2560 1376
 
Quality style: 0
 
Background on: True
 
Child safety: False
 
Game zoom: 1
 
UI zoom: 1
 
 
 
Recent error logs:
```
1:000:00000 - 000096.49   HamstarHelpers.PlayerDataProtocol.ReceiveOnClient - Inactive player indexed as 1
1:000:00001 - 000160.55   HamstarHelpers.PlayerDataProtocol.ReceiveOnClient - Inactive player indexed as 2
1:000:00002 - 001402.55   HamstarHelpers.PlayerDataProtocol.ReceiveOnClient - Inactive player indexed as 2
```
 
loweringmax blocks doesn't seem to do anything even after resetting terraria after changing the config file

**Comment by NanobotZ** [comment]
will be fixed soon ™
