### ISSUE TITLE
"Reported from in-game: can vein mine dirt" - submitted via. helper utility

### ISSUE THREAD

**Issue by hamstar0** [NanobotZ/tml_VeinMiner_mod#26]
tModLoader version: 0.11.7.7
 
| Mods:  | - | - |
| :--- | :--- | :--- |
| `Auto Drink Mana Potions 1.0` | `Auto Trash 0.5` | `Block Swap (From 1\.4) 1.0.1` |
| `Boss Checklist 1.1.4.1` | `Boss Cursor 1.5.1` | `Can I Mine It? 0.1` |
| `Starter packs 0.12` | `Chest Searching 1.0` | `The Clicker Class 1.1.12` |
| `Use Control to Quick Trash (From 1\.4) 1.1` | `Dacern's quality of life mod 0.2.1` | `Begone, Evil\! (Disable Evil Biome Spread) 1.1.1` |
| `Extensible Inventory 1.5.2.1` | `Faster Building 1.0.3.1` | `Mod Helpers 5.9.4` |
| `LadyFluffyPandas Extended Crafting Mod 0.3.4` | `Magic Storage 0.4.3.5` | `\[c/9370DB\:Mana Fruit Mod\] 0.1.2.1` |
| `Max Stack Plus Extra 1.1.0.4` | `More Chest Loot 0.6` | `No Hotbar Pickup 0.4.2` |
| `OmniSwing 3.0.1` | `Pumpking's Mod 1.1.4.1` | `Recipe Browser 0.8.7` |
| `Smart Doors (from 1\.4) 1.3.3` | `Friendly NPCs Don't Die 1.1` | `Upgraded Accessories 4.1` |
| `Upgrade Equipment 1.2.0` | `VeinMiner 1.3.1` | `WeaponOut 1.6.4` |
| `Wing Slot 1.7.3` | `Which Mod Is This From? (WMITF) 2.6.2` | `Yet Another Boss Summon Shop 1.0.0.6` |
 
| Name | Male | Has Demon Heart | Difficulty mode | Life | Mana | Defense |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| Ted | True | False | 0 | 260 of 260 | 40 of 40 | 9 |
 
**Player Ted's (0) equipment:**
 
| Head | Body | Legs | Vanity 1 | Vanity 2 | Vanity 3 |
| :--- | :--- | :--- | :--- | :--- | :--- |
| Ninja Hood | Ninja Shirt | Ninja Pants | Fox Mask | Fox Shirt | Fox Pants |
 
Is day: True, Time of day/night: 6184, Elapsed half days: 15
 
World name: God Mod V3, world size: Medium
 
World progress: Eye of Cthulhu killed, King Slime killed, Eater of Worlds killed, Skeletron killed
 
Items on ground: 74, Npcs active: 12
 
Player count: 1 (single-player)
 
Autopause: False
 
Autosave: True
 
Lighting mode: 0
 
Lighting threads: 0
 
Frame skip mode: 2
 
Is screen maximized: True
 
Screen resolution: 1920 1177
 
Quality style: 0
 
Background on: True
 
Child safety: False
 
Game zoom: 1
 
UI zoom: 1
 
FrameworkVersion.Framework: NetFramework
 
FrameworkVersion.Version: 4.8
 
 
 
Recent error logs:
```
...
[15:05:39] [23/INFO] [StatusText]: Saving world data
[15:05:39] [23/INFO] [StatusText]: Validating world save
[15:05:42] [30/INFO] [Terraria]: Loading World: God Mod V3, IsCloud=False
[15:05:43] [30/INFO] [StatusText]: Resetting game objects
[15:05:43] [30/INFO] [StatusText]: Loading world data
[15:05:43] [30/INFO] [StatusText]: Settling liquids
[15:05:44] [30/INFO] [StatusText]: Loading map data
[15:05:44] [30/INFO] [StatusText]: Drawing map
[15:05:44] [1/INFO] [Terraria]: Entering world with player: Ted, IsCloud=False
[15:07:30] [20/INFO] [StatusText]: Saving world data
[15:07:30] [20/INFO] [StatusText]: Validating world save
[15:17:30] [20/INFO] [StatusText]: Saving world data
[15:17:30] [20/INFO] [StatusText]: Validating world save
[15:27:30] [40/INFO] [StatusText]: Saving world data
[15:27:31] [40/INFO] [StatusText]: Validating world save
```
 
while holding the veinmine key and mining dirt, it will begin to hollow out the entire surface level of the world unless you leave the world.

**Comment by NanobotZ** [comment]
cancelling veinmining will come soon ™
