### ISSUE TITLE
Add to item to veinlist function does not work in multiplayer

### ISSUE THREAD

**Issue by JaydenIsAPig** [NanobotZ/tml_VeinMiner_mod#32]
Details, I run a local server (I personnaly host it, and port forwarded it), and when i play with my friend the function where you add something to the veinminer whitelist does not work, it works in single player, but not multiplayer

Thank you for the help, and for the amazing mod (this is genuinely one of the best terraria mods so keep up the great work!)

**Comment by NanobotZ** [comment]
By default that option is disabled on multiplayer.
Server host has to enable it in the config file (unfortunately this mod doesn't have in-game config support).
File is located in `Documents\My Games\Terraria\ModLoader\Mod Configs\VeinMiner.json`.
The option you'll be looking for is `"ModifyingWhitelistOnMultiplayer": false`, which you'd have to change to true and save the file.
