### ISSUE TITLE
"In-game: VeinMiner 1.3.0.5" - submitted via. helper utility

### ISSUE THREAD

**Issue by hamstar0** [NanobotZ/tml_VeinMiner_mod#4]
Mods: Better take a Power Tool 1.5.0.1, Boss Checklist 0.2, Calamity Mod 1.4.0.2, Chad's Furniture Mod 1.4.1, Craftable Vanity 1.0, Fun Death Sounds 1.2, Mod Helpers 3.1.0.4, Removed nerfs of items 3.0, Luiafk 1.0.0.130, Magic Storage 0.4.3.3, Max Stack Plus Extra 1.0.2, More Chest Loot 0.6, No More Tombs 1.0.1, OmniSwing 2.1, Reduced Grinding 4.33.1, Rewards 2.0.0, Shorter Respawn Time 0.2.5, VeinMiner 1.3.0.5
 
Is day: True, Time of day/night: 39746, Elapsed half days: 6
 
World name: Teste MODS, world size: Large
 
World progress: 
 
Items on ground: 80, Npcs active: 8
 
Player info: Name: `YaMMaZz`, Male: False, Demon Heart: False, Difficulty mode: 0, Life: 100 of 100, Mana: 40 of 40, Defense: 0
 
Player equips: Vanity: Chapéu de Neve, Vanity: Suéter Feio
 
Player count: 1 (single-player)
 
 
 
Recent error logs:
```
NoMoreTombs: Failed to read config file! Recreating config...
Failed to read config file! Recreating config...
Failed to read chadfurni's config file! Recreating config...
Failed to read Death Noises config file! Recreating config...
Mod Helpers updated to 3.1.0.4
Failed to read Removed nerfs of items config file! Recreating config...
Failed to read Reduced Grinding's config file! Recreating config...
Failed to read VeinMiner's config file! Recreating config...
[OmniSwing][2018-12-17 03:41:25] Config file not found, creating default...
Rewards updated to 2.0.0
Rewards updated to 2.0.0
0:000:00000 - 000144.86   RewardsWorld.Initialize
0:000:00001 - 000208.35   RewardsWorld.Initialize
0:000:00002 - 000208.52   RewardsWorld.Initialize
Mod configs reloaded for BettertakeaPowerTool, HamstarHelpers, ItemsBuffs, OmniSwing, Rewards, VeinMiner
Mod configs reloaded for BettertakeaPowerTool, HamstarHelpers, ItemsBuffs, OmniSwing, Rewards, VeinMiner
```
 
Don't work correctly

**Comment by NanobotZ** [comment]
Not enough information
