### ISSUE TITLE
"In-game: Doesn't work" - submitted via. helper utility

### ISSUE THREAD

**Issue by hamstar0** [NanobotZ/tml_VeinMiner_mod#5]
Mods: Just another Alchemist NPC 2.3, Auto Trash 0.3.1, Banner Bonanza 1.1, Better Buffs 1.2.1.2, Better Yoyos 0.2, Boss Checklist 0.2, Chad's Furniture Mod 1.4.1, Crystilium 11.3.1.5, Prefixes For Enemies 2.0.0, Extensible Inventory 1.2.1.4, Faster Tools 1.0.1, Yet Another Boss Health Bar 1.3.2, Botanist NPC 1.2.1, Mod Helpers 4.1.0.1, JoostMod 0.7.2.12, [c/9bffb9:Lighting Essentials] 0.5, Luiafk 1.0.0.130, Magic Storage 0.4.3.3, Max Stack Plus Extra 1.0.2, More Chest Loot 0.6, No More Tombs 1.0.1, OmniSwing 2.1, Ore Seeds 0.4.3, Plentiful Ores 1.3, Recipe Browser 0.7, [c/ff66ff:Sexy] [c/cc33ff:Purple] [c/ff66cc:Tooltips] 0.2, Simple Auto Chests 1.0.1, Terraria Tweaks 1.8.4.4, The Luggage 0.1.3, Thorium Mod 1.5.1.2, Useful Jungle Mimic Mod 1.0.1, VeinMiner 1.3.0.5, WeaponOut Lite 0.1, Wildlife Mod 0.11.2, Wing Slot 1.6.2, Which Mod Is This From? (WMITF) 2.6
 
Is day: True, Time of day/night: 40489, Elapsed half days: 6
 
World name: Reich, world size: Medium
 
World progress: 
 
Items on ground: 10, Npcs active: 8
 
Player info: Name: `Meteoru`, Male: True, Demon Heart: False, Difficulty mode: 0, Life: 100 of 100, Mana: 60 of 60, Defense: 4
 
Player equips: Accessory: Kletterklauen, Accessory: Rejuvenating Unruhige Stiefel, Accessory: Radar (Abwehrend)
 
Player count: 1 (single-player)
 
Autopause: False
 
Autosave: True
 
Lighting mode: 0
 
Lighting threads: 3
 
Frame skip mode: 0
 
Is screen maximized: False
 
Screen resolution: 1920 1080
 
Quality style: 1
 
Background on: False
 
Child safety: False
 
Game zoom: 1
 
UI zoom: 1
 
 
 
Recent error logs:
```
read version = 1
BannerBonanza: Warning, multiple BannerIDs pointing to same ItemID: Banners:Arctic Fox,Fox Item:Fox Banner
BannerBonanza: Warning, multiple BannerIDs pointing to same ItemID: Banners:Snake,Gold Snake Item:Snake Banner
```
 
I need to mine the ore's seperatly /

**Comment by NanobotZ** [comment]
Probably Veinmine keybind is not assigned to a key.
